language: node_js
if: branch != gh-pages
node_js:
  - lts/*

install:
  - npm ci

script:
  - npm run docs:build
  - echo 'primer.desmos.network' > .vuepress/dist/CNAME

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: .vuepress/dist
  github-token: $GITHUB_TOKEN
  keep-history: true