language: node_js
if: branch != gh-pages
node_js:
  - lts/*

install:
  - npm install
  - npm ci

script:
  - npm run docs:build
  - echo 'primer.desmos.network' > .vuepress/dist/CNAME
  - npm run build-scripts
  - npm run gather-data -- --csv-file-path=output.csv --scoreboard-file-path=scoreboard/scoreboard.md
  - npm run upload-data -- --csv-file-path=output.csv

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: .vuepress/dist
  github-token: $GITHUB_TOKEN
  keep-history: true
