# This workflow allows to publish the data from this repo to the proper PostgreSQL database on which all the data
# is hosted. This will later be used to fetch the public data and show them inside our custom website.
name: Data
on:
  pull_request:

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - Checkout:
        name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - Build:
        name: Build scripts âš™ï¸
        needs: Checkout
        run: |
          npm install
          npm run build-scripts

      - Check-txs:
        name: Check transactions ğŸ”
        needs: Build
        run: npm run check-txs

      - name: Publish ğŸš€
        needs: [Build, Check-txs]
        run: npm run publish-data
        env:
          PGHOST: ${{ secrets.PGHOST }}
          PGPORT: ${{ secrets.PGPORT }}
          PGUSER: ${{ secrets.PGUSER }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          PGDATABASE: ${{ secrets.PGDATABASE }}
