# This workflow allows to publish the data from this repo to the proper PostgreSQL database on which all the data
# is hosted. This will later be used to fetch the public data and show them inside our custom website.
name: Data publisher
on:
  pull_request:

jobs:
  Publish-data:
    runs-on: ubuntu-latest
      steps:
        - name: Checkout ğŸ›ï¸
          uses: actions/checkout@v2
          with:
            persist-credentials: false

        - name: Build scripts âš™ï¸
          run: |
            npm install
            npm ci
            npm run build-scripts

        - name: Check transactions ğŸ”
          run: npm run check-txs

        - name: Publish ğŸš€
          run: npm run publish-data
          with:
            PGHOST: ${{ secrets.PGHOST }}
            PGPORT: ${{ secrets.PGPORT }}
            PGUSER: ${{ secrets.PGUSER }}
            PGPASSWORD: ${{ secrets.PGPASSWORD }}
            PGDATABASE: ${{ secrets.PGDATABASE }}
