name: Tests & Docs
on:
  push:
    branches:
      - master

  pull_request:

jobs:

  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build scripts âš™ï¸
        run: |
          npm install
          npm ci
          npm run build-scripts

      - name: Check transactions
        run: npm run check-txs

      - name: Build docs ðŸ“ƒ
        run: |
          npm run gather-data -- --csv-file-path=output.csv --scoreboard-file-path=scoreboard.md
          npm run upload-data -- --csv-file-path=output.csv
          npm run docs:build
          echo 'primer.desmos.network' > .vuepress/dist/CNAME

      - name: Deploy ðŸš€
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: .vuepress/dist
